### ISSUE TITLE
"Failed to unpack" select.zxp - Illustrator CC-2014

### ISSUE THREAD

**Issue by vertigocreative** [smorodsky/Select#1]
Can you help me get this installed?

Extension Manager says "Failed to unpack the zxp file. Please make sure the extension is valid. the extension will not be installed."

When I try to install from Adobe Add-ons I get "error 402".

Thank you!

**Comment by smorodsky** [comment]
Work in the CC-2014 has not yet been tested. You can try to manually install:
- rename _select.zxp_ to _select.zip_
- unpack _select.zip_
- place all files to folder _/Applications/Adobe Illustrator CC/Presets/en_GB/Scripts/Select_
- restart Illustrator

**Comment by vertigocreative** [comment]
That worked! Looks like you need to work on making the select.zxp compatible with Extension Manager. 

![screenclip](https://cloud.githubusercontent.com/assets/8052590/3496185/7a13db80-05df-11e4-8ad7-ab4f76b6b409.png)
